# Generated by Django 3.2.6 on 2021-08-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
