# Generated by Django 3.2.6 on 2021-08-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
