# Generated by Django 3.2.6 on 2021-08-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField(verbose_name='Description')),
                ('measure', models.CharField(max_length=50, verbose_name='Measure')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=20, verbose_name='category')),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
    ]
