# Generated by Django 3.2.6 on 2021-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('ordered_on', models.DateTimeField(auto_now_add=True)),
                ('order_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
