# Generated by Django 3.2.6 on 2021-08-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descrption',
            field=models.TextField(default='Product Description', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
