# Generated by Django 3.2.6 on 2021-08-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_product_price'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='ParentCategory',
        # ),
        # migrations.DeleteModel(
        #     name='SubCategory',
        # ),
        migrations.RenameField(
            model_name='product',
            old_name='descrption',
            new_name='description',
        ),
    ]
